name: Tests
on:
  push:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Tests
      run: make test
    
    - name: Build all binaries
      run: make .build-release
